-- GramStack Individual Columns Migration
-- Automatically executed upon deployment to ensure all 6 registries' columns exist in individuals tables

DO $$
BEGIN
    -- 0. Fix missing core platform columns
    ALTER TABLE g2p_intake_form_submissions ADD COLUMN IF NOT EXISTS application_reference VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS application_reference VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS application_reference VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS application_reference VARCHAR;
    ALTER TABLE g2p_intake_form_households ADD COLUMN IF NOT EXISTS application_reference VARCHAR;
    ALTER TABLE g2p_register_households ADD COLUMN IF NOT EXISTS application_reference VARCHAR;
    ALTER TABLE g2p_register_history_households ADD COLUMN IF NOT EXISTS application_reference VARCHAR;
    ALTER TABLE g2p_registry_configuration ADD COLUMN IF NOT EXISTS registry_favicon VARCHAR;

    -- 1. Common Location, Personal & Financial Identifiers
    -- g2p_register_individuals
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS household_id VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS mobile_number VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS bank_account_no VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS district VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS block VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS village VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS gp VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS aadhaar_number VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS dob VARCHAR;

    -- g2p_intake_form_individuals
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS household_id VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS mobile_number VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS bank_account_no VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS district VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS block VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS village VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS gp VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS aadhaar_number VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS dob VARCHAR;

    -- g2p_register_history_individuals
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS household_id VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS mobile_number VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS bank_account_no VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS district VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS block VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS village VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS gp VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS aadhaar_number VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS dob VARCHAR;

    -- 2. JEEViKA SHG LokOS
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS member_id VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS shg_id VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS shg_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS vo_id VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS vo_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS clf_id VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS clf_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS member_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS relationship_to_hoh VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS shg_role VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS shg_join_date VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS shg_grading VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS monthly_savings_amount NUMERIC(12, 2);
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS internal_loan_outstanding NUMERIC(12, 2);
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS ccl_limit BIGINT;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS ccl_utilised NUMERIC(12, 2);
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS ifsc VARCHAR;

    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS member_id VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS shg_id VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS shg_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS vo_id VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS vo_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS clf_id VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS clf_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS member_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS relationship_to_hoh VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS shg_role VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS shg_join_date VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS shg_grading VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS monthly_savings_amount NUMERIC(12, 2);
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS internal_loan_outstanding NUMERIC(12, 2);
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS ccl_limit BIGINT;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS ccl_utilised NUMERIC(12, 2);
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS ifsc VARCHAR;

    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS member_id VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS shg_id VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS shg_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS vo_id VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS vo_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS clf_id VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS clf_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS member_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS relationship_to_hoh VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS shg_role VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS shg_join_date VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS shg_grading VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS monthly_savings_amount NUMERIC(12, 2);
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS internal_loan_outstanding NUMERIC(12, 2);
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS ccl_limit BIGINT;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS ccl_utilised NUMERIC(12, 2);
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS ifsc VARCHAR;

    -- 3. BiharBhumi Land Records
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS jamabandi_number VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS khata_number VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS khesra_numbers VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS rayat_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS rakba_area NUMERIC(12, 2);
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS land_type VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS mauza VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS anchal VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS mutation_status VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS last_mutation_date VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS lpc_status VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS lpc_certificate_number VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS encumbrance_status VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS bhu_lagan_paid_status BOOLEAN;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS registration_deed_number VARCHAR;

    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS jamabandi_number VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS khata_number VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS khesra_numbers VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS rayat_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS rakba_area NUMERIC(12, 2);
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS land_type VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS mauza VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS anchal VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS mutation_status VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS last_mutation_date VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS lpc_status VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS lpc_certificate_number VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS encumbrance_status VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS bhu_lagan_paid_status BOOLEAN;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS registration_deed_number VARCHAR;

    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS jamabandi_number VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS khata_number VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS khesra_numbers VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS rayat_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS rakba_area NUMERIC(12, 2);
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS land_type VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS mauza VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS anchal VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS mutation_status VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS last_mutation_date VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS lpc_status VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS lpc_certificate_number VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS encumbrance_status VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS bhu_lagan_paid_status BOOLEAN;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS registration_deed_number VARCHAR;

    -- 4. Farmer AgriStack
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS farmer_id VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS farmer_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS relation_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS khatiyan_number VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS khesra_number VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS land_area_acres NUMERIC(12, 2);
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS land_ownership_type VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS crop_type VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pm_kisan_enrolled BOOLEAN;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pmfby_enrolled BOOLEAN;

    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS farmer_id VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS farmer_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS relation_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS khatiyan_number VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS khesra_number VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS land_area_acres NUMERIC(12, 2);
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS land_ownership_type VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS crop_type VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pm_kisan_enrolled BOOLEAN;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pmfby_enrolled BOOLEAN;

    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS farmer_id VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS farmer_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS relation_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS khatiyan_number VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS khesra_number VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS land_area_acres NUMERIC(12, 2);
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS land_ownership_type VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS crop_type VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pm_kisan_enrolled BOOLEAN;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pmfby_enrolled BOOLEAN;

    -- 5. PDS Food Security (Ration Card)
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS ration_card_number VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS ration_card_type VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS head_of_household_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS family_member_count BIGINT;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS fps_shop_code VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS dealer_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS e_kyc_status VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS last_transaction_date VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS monthly_entitlement_kg BIGINT;

    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS ration_card_number VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS ration_card_type VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS head_of_household_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS family_member_count BIGINT;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS fps_shop_code VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS dealer_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS e_kyc_status VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS last_transaction_date VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS monthly_entitlement_kg BIGINT;

    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS ration_card_number VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS ration_card_type VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS head_of_household_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS family_member_count BIGINT;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS fps_shop_code VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS dealer_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS e_kyc_status VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS last_transaction_date VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS monthly_entitlement_kg BIGINT;

    -- 6. Student (UDISE+)
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS student_aadhaar_number VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS guardian_aadhaar_number VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS udise_student_id VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS student_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS school_udise_code VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS school_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS class_grade VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS enrollment_date VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS attendance_percentage NUMERIC(12, 2);
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS scholarship_status VARCHAR;

    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS student_aadhaar_number VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS guardian_aadhaar_number VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS udise_student_id VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS student_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS school_udise_code VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS school_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS class_grade VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS enrollment_date VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS attendance_percentage NUMERIC(12, 2);
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS scholarship_status VARCHAR;

    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS student_aadhaar_number VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS guardian_aadhaar_number VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS udise_student_id VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS student_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS school_udise_code VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS school_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS class_grade VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS enrollment_date VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS attendance_percentage NUMERIC(12, 2);
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS scholarship_status VARCHAR;

    -- 7. Social Pension
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS beneficiary_id VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS scheme_name VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS sanction_date VARCHAR;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pension_amount_monthly BIGINT;
    ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS payment_status VARCHAR;

    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS beneficiary_id VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS scheme_name VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS sanction_date VARCHAR;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pension_amount_monthly BIGINT;
    ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS payment_status VARCHAR;

    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS beneficiary_id VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS scheme_name VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS sanction_date VARCHAR;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pension_amount_monthly BIGINT;
    ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS payment_status VARCHAR;
END $$;


BEGIN;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS religion VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS caste VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS aadhaar_no VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS primary_phone_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS gram_panchayat VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pin_code VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS bank_name VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS shg_member_name VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS shg_bank_account_no VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS shg_ifsc VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS khatian_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS plot_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS total_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS irrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS unirrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS land_classification VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS soil_type VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pm_kisan_id VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pm_kisan_status VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pm_kisan_installment_count INTEGER;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS primary_crop VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS secondary_crop VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS kcc_sanctioned_amount NUMERIC(12, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS kcc_outstanding_amount NUMERIC(12, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS soil_health_card_issued BOOLEAN;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS crop_insurance_enrolled BOOLEAN;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pds_ration_card_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pds_card_type VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS fps_dealer_name VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pds_family_member_count INTEGER;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS last_pds_transaction_date VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pds_ekyc_status VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pension_scheme_name VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pensioner_id VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS sanction_order_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS monthly_pension_amount NUMERIC(10, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pension_disbursement_mode VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pension_account_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pension_status VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS last_disbursement_date VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS student_id VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS current_grade VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS scholarship_received VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS midday_meal_beneficiary BOOLEAN;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS religion VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS caste VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS aadhaar_no VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS primary_phone_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS gram_panchayat VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pin_code VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS bank_name VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS shg_member_name VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS shg_bank_account_no VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS shg_ifsc VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS khatian_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS plot_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS total_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS irrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS unirrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS land_classification VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS soil_type VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pm_kisan_id VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pm_kisan_status VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pm_kisan_installment_count INTEGER;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS primary_crop VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS secondary_crop VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS kcc_sanctioned_amount NUMERIC(12, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS kcc_outstanding_amount NUMERIC(12, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS soil_health_card_issued BOOLEAN;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS crop_insurance_enrolled BOOLEAN;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pds_ration_card_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pds_card_type VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS fps_dealer_name VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pds_family_member_count INTEGER;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS last_pds_transaction_date VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pds_ekyc_status VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pension_scheme_name VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pensioner_id VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS sanction_order_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS monthly_pension_amount NUMERIC(10, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pension_disbursement_mode VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pension_account_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pension_status VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS last_disbursement_date VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS student_id VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS current_grade VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS scholarship_received VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS midday_meal_beneficiary BOOLEAN;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS religion VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS caste VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS aadhaar_no VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS primary_phone_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS gram_panchayat VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pin_code VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS bank_name VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS shg_member_name VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS shg_bank_account_no VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS shg_ifsc VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS khatian_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS plot_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS total_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS irrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS unirrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS land_classification VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS soil_type VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pm_kisan_id VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pm_kisan_status VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pm_kisan_installment_count INTEGER;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS primary_crop VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS secondary_crop VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS kcc_sanctioned_amount NUMERIC(12, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS kcc_outstanding_amount NUMERIC(12, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS soil_health_card_issued BOOLEAN;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS crop_insurance_enrolled BOOLEAN;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pds_ration_card_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pds_card_type VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS fps_dealer_name VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pds_family_member_count INTEGER;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS last_pds_transaction_date VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pds_ekyc_status VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pension_scheme_name VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pensioner_id VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS sanction_order_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS monthly_pension_amount NUMERIC(10, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pension_disbursement_mode VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pension_account_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pension_status VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS last_disbursement_date VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS student_id VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS current_grade VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS scholarship_received VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS midday_meal_beneficiary BOOLEAN;
COMMIT;