BEGIN;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS religion VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS caste VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS aadhaar_no VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS primary_phone_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS gram_panchayat VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pin_code VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS bank_name VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS shg_member_name VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS shg_bank_account_no VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS shg_ifsc VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS khatian_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS plot_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS total_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS irrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS unirrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS land_classification VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS soil_type VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pm_kisan_id VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pm_kisan_status VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pm_kisan_installment_count INTEGER;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS primary_crop VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS secondary_crop VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS kcc_sanctioned_amount NUMERIC(12, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS kcc_outstanding_amount NUMERIC(12, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS soil_health_card_issued BOOLEAN;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS crop_insurance_enrolled BOOLEAN;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pds_ration_card_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pds_card_type VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS fps_dealer_name VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pds_family_member_count INTEGER;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS last_pds_transaction_date VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pds_ekyc_status VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pension_scheme_name VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pensioner_id VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS sanction_order_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS monthly_pension_amount NUMERIC(10, 2);
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pension_disbursement_mode VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pension_account_number VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS pension_status VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS last_disbursement_date VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS student_id VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS current_grade VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS scholarship_received VARCHAR;
ALTER TABLE g2p_register_individuals ADD COLUMN IF NOT EXISTS midday_meal_beneficiary BOOLEAN;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS religion VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS caste VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS aadhaar_no VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS primary_phone_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS gram_panchayat VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pin_code VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS bank_name VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS shg_member_name VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS shg_bank_account_no VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS shg_ifsc VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS khatian_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS plot_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS total_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS irrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS unirrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS land_classification VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS soil_type VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pm_kisan_id VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pm_kisan_status VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pm_kisan_installment_count INTEGER;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS primary_crop VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS secondary_crop VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS kcc_sanctioned_amount NUMERIC(12, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS kcc_outstanding_amount NUMERIC(12, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS soil_health_card_issued BOOLEAN;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS crop_insurance_enrolled BOOLEAN;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pds_ration_card_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pds_card_type VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS fps_dealer_name VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pds_family_member_count INTEGER;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS last_pds_transaction_date VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pds_ekyc_status VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pension_scheme_name VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pensioner_id VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS sanction_order_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS monthly_pension_amount NUMERIC(10, 2);
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pension_disbursement_mode VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pension_account_number VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS pension_status VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS last_disbursement_date VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS student_id VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS current_grade VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS scholarship_received VARCHAR;
ALTER TABLE g2p_intake_form_individuals ADD COLUMN IF NOT EXISTS midday_meal_beneficiary BOOLEAN;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS religion VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS caste VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS aadhaar_no VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS primary_phone_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS gram_panchayat VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pin_code VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS bank_name VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS shg_member_name VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS shg_bank_account_no VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS shg_ifsc VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS khatian_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS plot_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS total_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS irrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS unirrigated_land_area_acres NUMERIC(10, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS land_classification VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS soil_type VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pm_kisan_id VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pm_kisan_status VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pm_kisan_installment_count INTEGER;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS primary_crop VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS secondary_crop VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS kcc_sanctioned_amount NUMERIC(12, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS kcc_outstanding_amount NUMERIC(12, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS soil_health_card_issued BOOLEAN;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS crop_insurance_enrolled BOOLEAN;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pds_ration_card_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pds_card_type VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS fps_dealer_name VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pds_family_member_count INTEGER;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS last_pds_transaction_date VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pds_ekyc_status VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pension_scheme_name VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pensioner_id VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS sanction_order_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS monthly_pension_amount NUMERIC(10, 2);
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pension_disbursement_mode VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pension_account_number VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS pension_status VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS last_disbursement_date VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS student_id VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS current_grade VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS scholarship_received VARCHAR;
ALTER TABLE g2p_register_history_individuals ADD COLUMN IF NOT EXISTS midday_meal_beneficiary BOOLEAN;
COMMIT;